### ISSUE TITLE
Make available on npm

### ISSUE THREAD

**Issue by crazy4groovy** [douglascrockford/RQ#21]
I think there will be wider adoption of this lib if it is published on npm.

**Comment by douglascrockford** [comment]
Given its inherent security problems, I cannot recommend that anyone use NPM.

**Comment by ajhyndman** [comment]
@douglascrockford Any chance you could reference some of the security problems you're concerned with?

**Comment by toverux** [comment]
We can't blame you for being so defensive...
However, did you see the progress on this matter with npm 5.x? [yarn](https://yarnpkg.com) is also an alternative.

**Comment by GrosSacASac** [comment]
I can't blame douglas for trying to prevent us from the dangers of npm.

NPM by design is a glorified copy paste ... where you don't even look at the code. So there's that.

Also how do can we look that a package is authentic before downloading it ? What if a sub-sub-sub dependency is in fact malicious code because the main author's account got compromised 2 weeks ago ?

Serious security issues that are by design in npm and I personally would still put my code on npm because if developers are going to copy paste my code without reading it, npm or github is not going to change that.
